### ISSUE TITLE
Vérifier l'affichage des informations des features et créer un json comprenant le nom des propriétés à afficher

### ISSUE THREAD

**Issue by Bmaeve** [Bmaeve/TRIvial#116]
### Nom de la branche
CkeckDisplayInfosFeatureCreateJson

### Description
US du Back.
Vérifier l'affichage/le visuel des informations des features.
Créer un fichier .json comprenant le nom des propriétés à afficher dans les informations des features, dans le but de simplifier et d'améliorer le visuel.

### Préconditions (dépendance):
* [Afficher les informations d'un enjeu en cliquant dessus](https://github.com/Bmaeve/TRIvial/issues/71)

### Critères d’acceptation :
Scénario 1 : L'affichage des informations des features est correct.

**Comment by Emmaloup13** [comment]
done
