### ISSUE TITLE
Afficher une couche par type d'enjeu

### ISSUE THREAD

**Issue by Emmaloup13** [Bmaeve/TRIvial#78]
### Nom de la branche
AfficherCoucheType

### Description
US du Front/Back.
Changer la fonction api2itowns pour créer une couche par type d'enjeu et jouer sur l'attribut visible de celles-ci afin pour essayer de régler les problèmes existants.

### Préconditions (dépendance):
* [Lier les sélections avec l'API](https://github.com/Bmaeve/TRIvial/issues/34)

### Critères d’acceptation :
Scénario 1 : on sélectionne des enjeux et types d'enjeux et lorsqu'on change la sélection, les couches s'affichent comme voulu, elles ne disparaissent pas.

**Comment by Emmaloup13** [comment]
Very long loading, API errors to look at on friday, "layerMask = 31" and similar issue on itowns' github :  https://github.com/iTowns/itowns/issues/1863

**Comment by Emmaloup13** [comment]
Issue laissée à l'abandon, ne pas reprendre

**Comment by baptisteRiviere** [comment]
😿😿😿😿
