### ISSUE TITLE
Réflexion sur la Maquette

### ISSUE THREAD

**Issue by Bmaeve** [Bmaeve/TRIvial#8]
### Nom de la branche
MaquetteFront

### Description
US du Front.
Réfléchir et faire un point sur la maquette visuelle de la solution. A l'aide de Draw.io ou Canva, une pré-viusalisation (sans interaction) sera produite. Les interactions à cette maquette (Front-Back) seront pensées

### Préconditions (dépendance):
Aucune.

### Critères d’acceptation :
Scénario 1 : La maquette sera visualisable.

**Comment by Emmaloup13** [comment]
Maquette présente sur le One Drive, dans le dossier UML, visualisable via draw.io. Peut être modifiée facilement
